spring:
  datasource:
    url: jdbc:mysql://localhost:3307/beneficios?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  logging:
    level:
      org.springframework: DEBUG